In [4]:
import numpy as np
import pandas as pd

In [5]:
# 배열만들기
#리스트 배열 만들기
ls1 = list(range(10))
print(ls1,type(ls1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>


In [6]:
# array 배열 만들기
arr1 = np.array(range(1,6))
print(arr1,type(arr1))
arr2 = np.array([1,2,3,4,5])
print(arr2,arr2.dtype)
arr3 = np.array([3,1.4,2,3,4,5]) #소수가 있는 경우
print(arr3,arr3.dtype) #넘파이의 array 는 단일 데이터 타입이다
arr4 = np.array([ [1,2], [3,4]])
print(arr4)
arr5 = np.array( [1,2,3,4], dtype=float) #dtype 변환
print(arr5,arr5.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'>
[1 2 3 4 5] int64
[3.  1.4 2.  3.  4.  5. ] float64
[[1 2]
 [3 4]]
[1. 2. 3. 4.] float64


In [7]:
# dtype / astype : change the type
arr1 = np.array([1,2,3,4],dtype=float)
print(arr1,arr1.dtype)
arr1.astype(float)
print(arr1.dtype)

[1. 2. 3. 4.] float64
float64


In [8]:
# zeros . ones . arrange . linspace
print(np.zeros(10,dtype=int))
print(np.ones( (3,5), dtype=float))
print(np.arange(0,20,2))
print(np.linspace(0,1,5))

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]


In [9]:
print(np.random.random( (2,3)))
print( np.random.normal(0,2, (2,2))) # mean, std, array
print( np.random.randint(0,10, (2,2))) # start , stop , array

[[0.32196    0.94646426 0.51806852]
 [0.80704361 0.5831643  0.87562628]]
[[-1.01163118 -4.43367163]
 [-3.03961501 -2.36800541]]
[[5 7]
 [8 7]]


In [10]:
# random vs rand ?
# 0~1 사이에 난수 생성 
print(np.random.random( (2,2))) # 형태를 받는다 
print(np.random.rand(2,2)) # 직접 차원을 인수를 넣어준다 

[[0.86100805 0.57310263]
 [0.90942301 0.52633336]]
[[0.90132727 0.99384424]
 [0.58837733 0.52941996]]


In [11]:
# dim , shape , size ,dtype 
x = np.random.randint(10,size=(3,4))
print(x.ndim) #차원 수 dimension
print(x.shape) #배열 
print(x.size) #요소의 수
print(x.dtype) # 데이터 타입

2
(3, 4)
12
int64


In [12]:
# indexing
x = np.arange(7)
print(x)
print(x[3])
print(x[-1])
print(x[0])
x[0] = 100 # 인덱스를 이용해 값을 치환할 수 도 있다 
print(x)

[0 1 2 3 4 5 6]
3
6
0
[100   1   2   3   4   5   6]


In [13]:
# slicing 
x = np.arange(7)
print(x)
print(x[1:4])
print(x[:4])
print(x[2:])
print(x[::2])
print(x[::-1])

[0 1 2 3 4 5 6]
[1 2 3]
[0 1 2 3]
[2 3 4 5 6]
[0 2 4 6]
[6 5 4 3 2 1 0]


In [14]:
# reshape 
x = np.arange(8)
x =x.reshape(2,-1)
print(x,x.shape)
x = x.flatten() #다시 하나의 배열로
print(x,x.shape)

[[0 1 2 3]
 [4 5 6 7]] (2, 4)
[0 1 2 3 4 5 6 7] (8,)


In [15]:
# concatenate
x1 = np.arange(3)
x2 = np.arange(3,6)
np.concatenate([x1,x2]) # 이어붙여준다 

array([0, 1, 2, 3, 4, 5])