In [3]:
!pip list 

Package                           Version
--------------------------------- ------------
aiobotocore                       2.7.0
aiohttp                           3.9.3
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.12
altair                            5.0.1
anaconda-anon-usage               0.4.3
anaconda-catalogs                 0.2.0
anaconda-client                   1.12.3
anaconda-cloud-auth               0.1.4
anaconda-navigator                2.5.3
anaconda-project                  0.11.1
anyio                             4.2.0
appdirs                           1.4.4
applaunchservices                 0.3.0
appnope                           0.1.2
appscript                         1.1.2
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
astroid                           2.14.2
astropy                  

In [2]:
import numpy as np
import pandas as pd

In [4]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])
arr1, arr2

(array([1, 2, 3, 4, 5]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [6]:
# 난수 이용한 2차원 배열 
# randn() : random + normal distribution
arr3 = np.random.randn(3)
arr4 = np.random.randn(2,3)

arr3,arr4

(array([-0.14680707,  0.10328271, -0.73083496]),
 array([[ 0.50696967,  0.7512807 , -0.6348419 ],
        [ 2.05522416, -0.98077556,  0.4025814 ]]))

In [8]:
arr5 = np.zeros(5)
arr6 = np.ones((2,3))

arr5,arr6

(array([0., 0., 0., 0., 0.]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [13]:
# arange() : array(배열) + range(범위)
# arange(start, end, step)

arr7 = np.arange(20,200,10)
arr7

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140,
       150, 160, 170, 180, 190])

In [17]:
# reshape()

print(len(arr7))
arr8 = arr7.reshape(3,-1)
arr8

18


array([[ 20,  30,  40,  50,  60,  70],
       [ 80,  90, 100, 110, 120, 130],
       [140, 150, 160, 170, 180, 190]])

In [28]:
# 배열 
print(len(arr9))
arr9 = np.arange(1,21)
arr9,arr9[1]
arr10 = arr9.reshape(4,-1)
print(arr10,arr10.shape)
print(arr10[3,0],arr10[3])

20
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] (4, 5)
16 [16 17 18 19 20]


In [29]:
arr10[3,0] = 116
arr10

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [116,  17,  18,  19,  20]])

In [31]:
# broadcasting : 각 원소에 적용 

arr11 = np.arange(1,11,1)
arr11 =arr11 + 3 
arr11

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [37]:
# 배열의 통계 메소드 

arr1 = np.array([ [5,7,9], [-7,6,19], [6,9,11] ])
print(arr1)
print('sum :',arr1.sum())
print('mean :',arr1.mean())
print('max :',arr1.max())

[[ 5  7  9]
 [-7  6 19]
 [ 6  9 11]]
sum : 65
mean : 7.222222222222222
max : 19


In [43]:
# axis : 배열의 축 지정 

print(arr1)
print()
print(arr1.max(axis=0))
print()
print(arr1.max(axis=1))

[[ 5  7  9]
 [-7  6 19]
 [ 6  9 11]]

[ 6  9 19]

[ 9 19 11]


In [44]:
# 조건식을 사용한 연산

arr1 > 0

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [45]:
arr1 < 0

array([[False, False, False],
       [ True, False, False],
       [False, False, False]])

In [47]:
arr1[arr1 > 5]

array([ 7,  9,  6, 19,  6,  9, 11])

In [49]:
# true 의 개수 반환
(arr1 > 3).sum()

8

In [53]:
# np.where
# 조건 : arr1 보다 작으면 / 참일때 반환값: 0 / 거짓일때 반환값: arr 
# 값을 치환할때 사용할수도 있을듯 
# ex) - 값을 치환할때 

np.where( arr1 < 0, 0, arr1)

array([[ 5,  7,  9],
       [ 0,  6, 19],
       [ 6,  9, 11]])

In [59]:

arr2 = np.array([ [5,7,9], [-3,6,19], [6,4,11] ])
print(arr2)

# 열 단위로 원소 정렬  
arr2.sort(0)
print(arr2)

[[ 5  7  9]
 [-3  6 19]
 [ 6  4 11]]
[[-3  4  9]
 [ 5  6 11]
 [ 6  7 19]]


In [61]:
arr2 = np.array([ [5,7,9], [-3,6,19], [6,4,11] ])

# 행 단위로 원소 정렬 
arr2.sort(1)
print(arr2)

[[ 5  7  9]
 [-3  6 19]
 [ 4  6 11]]


In [68]:
# 2차원축 -> 3차원 축 추가 방법
# 방법1 

arr1 = np.array([ [1,2,3], [4,5,6]])
print(arr1)
print()
# 첫번째 축에 새로운 축 추가
new_ax0 = arr[np.newaxis, : : ]
print(new_ax0)

print()
# 두번째 축에 새로운 축 추가 
new_ax1 = arr[:, np.newaxis, :]
print(new_ax1)

print()
# 세번째 축에 새로운 축 추가
new_ax2 = arr[:,:,np.newaxis]
print(new_ax2)

[[1 2 3]
 [4 5 6]]

[[[1 2 3]
  [4 5 6]]]

[[[1 2 3]]

 [[4 5 6]]]

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [69]:
np.zeros_like([[1,2,3],[4,5,6]])

array([[0, 0, 0],
       [0, 0, 0]])

In [75]:
# np.full((행,열),값)

np.full(3,3) , np.full((2,3),4)

(array([3, 3, 3]),
 array([[4, 4, 4],
        [4, 4, 4]]))

In [80]:
# random : 임의의 값으로 나타내준다 
np.random.random((3,4)) 
# 튜플 형태의 인자 (3,4)
# 한번만 전달받음

array([[0.76152477, 0.92969987, 0.84834368, 0.85172229],
       [0.97729114, 0.21308347, 0.74125967, 0.99129862],
       [0.50327956, 0.03244158, 0.70476367, 0.52685015]])

In [82]:
np.random.rand(3,4)
# 사실 둘의 기능은 똑같다 
# 0~1 사이이에서 난수 생성
# 여러개 인자를 전달 받을수 있음 

array([[0.64778387, 0.49947268, 0.85663367, 0.95558908],
       [0.26042473, 0.94700933, 0.35446321, 0.19800179],
       [0.34741947, 0.19821447, 0.88981606, 0.48675939]])

In [84]:
np.random.rand(3,4,2) # 정규화 
# 정규화 > 표준화 

array([[[0.84375576, 0.14674197],
        [0.88199342, 0.36737638],
        [0.69345984, 0.09997144],
        [0.45901007, 0.20370877]],

       [[0.86007944, 0.66357678],
        [0.5127811 , 0.49793271],
        [0.91043564, 0.19798303],
        [0.58147938, 0.30909273]],

       [[0.79670281, 0.21598244],
        [0.14259278, 0.77151742],
        [0.35029963, 0.15113646],
        [0.67015541, 0.51664927]]])

In [90]:
# np.eye() : 항등행렬

I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [88]:
A = np.array([ [2,3,1,5],
             [8,1,3,4],
             [5,6,7,8],
             [1,2,3,4] ])
A

array([[2, 3, 1, 5],
       [8, 1, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [91]:
A @ I

array([[2., 3., 1., 5.],
       [8., 1., 3., 4.],
       [5., 6., 7., 8.],
       [1., 2., 3., 4.]])

In [94]:
# 넘파이 배열 및 크기 변형 

arr = np.arange(12).reshape(12,-1)

In [96]:
# order='F' : 값을 열부터 채워넣는다
arr.reshape(4,-1,order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [97]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
# 4분위수 
x = np.arange([[1,2,3,4,5,6]])
np.percentile( (x,25) ) #1사분위수
np.percentile( (x,50) ) #중위수 2사분위수
np.percentile( (x,75) ) #3사분위수

TypeError: unsupported operand type(s) for -: 'list' and 'int'